=== Bismaon/COTWQ-client/public/assets/xml/countries_data.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="countries">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="country" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element minOccurs="1" name="en" type="xs:string"/>
                                        <xs:element minOccurs="1" name="fr" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="location" type="xs:string"/>
                            <xs:element name="territories" >
                                <xs:complexType>
                                    <xs:sequence >
                                        <xs:element name="territory"  maxOccurs="unbounded"
                                            type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="ownedLocation" type="xs:string"/>
                            <xs:element name="acceptedNames">
                                <xs:complexType>
                                    <xs:sequence  maxOccurs="unbounded">
                                        <xs:element name="name">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element minOccurs="1" name="en" type="xs:string"/>
                                                    <xs:element minOccurs="1" name="fr" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="flag">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="svg"  type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="currency" type="xs:string"  />
                            <xs:element name="languages">
                                <xs:complexType>
                                    <xs:sequence  maxOccurs="unbounded">
                                        <xs:element name="language" >
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element minOccurs="1" name="en" type="xs:string"/>
                                                    <xs:element minOccurs="1" name="fr" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="capital" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Bismaon/COTWQ-client/public/assets/xml/countries_data.xml
<?xml version='1.0' encoding='utf-8'?>
<countries xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./countries_data.xsd">
    <country>
        <name>
            <en>Algeria
            </en>
            <fr>Algérie</fr>
        </name>
        <location>
            0,0
        </location>
        <territories>
            <territory/>
        </territories>
        <ownedLocation/>
        <acceptedNames>
            <name>
                <en>Algeria</en>
                <fr>Algérie</fr>
            </name>
        </acceptedNames>
        <flag>
            <svg>
                dz.svg
            </svg>

        </flag>
        <currency>
            DZD
        </currency>
        <languages>
            <language>
                <en>Arabic</en>
                <fr>arabe</fr>
            </language>
            <language>
                <en>Tamazight</en>
                <fr>Tamazight</fr>
            </language>
        </languages>
        <capital>
            Algiers
        </capital>
    </country>
    <country>
        <name>
            <en>Angola
            </en>
            <fr>Angola</fr>
        </name>
        <location>
            0,1
        </location>
        <territories>
            <territory/>
        </territories>
        <ownedLocation/>
        <acceptedNames>
            <name>
                <en>Angola</en>
                <fr>Angola</fr>
            </name>
        </acceptedNames>
        <flag>
            <svg>
                ao.svg
            </svg>

        </flag>
        <currency>
            AOA
        </currency>
        <languages>
            <language>
                <en>Portuguese</en>
                <fr>portugais</fr>
            </language>
        </languages>
        <capital>
            Luanda
        </capital>
    </country>
    <country>
        <name>
            <en>Benin
            </en>
            <fr>Bénin</fr>
        </name>
        <location>
            0,2
        </location>
        <territories>
            <territory/>
        </territories>
        <ownedLocation/>
        <acceptedNames>
            <name>
                <en>Benin</en>
                <fr>Bénin</fr>
            </name>
        </acceptedNames>
        <flag>
            <svg>
                bj.svg
            </svg>

        </flag>
        <currency>
            XOF
        </currency>
        <languages>
            <language>
                <en>French</en>
                <fr>Français</fr>
            </language>
        </languages>
        <capital>
            Porto Novo
        </capital>
    </country>
    <country>
        <name>
            <en>Botswana
            </en>
            <fr>Botswana</fr>
        </name>
        <location>
            0,3
        </location>
        <territories>
            <territory/>
        </territories>
        <ownedLocation/>
        <acceptedNames>
            <name>
                <en>Botswana</en>
                <fr>Botswana</fr>
            </name>
        </acceptedNames>
        <flag>
            <svg>
                bw.svg
            </svg>

        </flag>
        <currency>
            BWP
        </currency>
        <languages>
            <language>
                <en>English</en>
                <fr>Anglais</fr>
            </language>
            <language>
                <en>Tswana</en>
                <fr>Tswana</fr>
            </language>
        </languages>
        <capital>
            Gaborone
        </capital>
    </country>
    <country>
        <name>
            <en>Burkina Faso
            </en>
            <fr>Burkina Faso</fr>
        </name>
        <location>
            0,4
        </location>
        <territories>
            <territory/>
        </territories>
        <ownedLocation/>
        <acceptedNames>
            <name>
                <en>Burkina Faso</en>
                <fr>Burkina Faso</fr>
            </name>
        </acceptedNames>
        <flag>
            <svg>
                bf.svg
            </svg>

        </flag>
        <currency>
            XOF
        </currency>
        <languages>
            <language>
                <en>French</en>
                <fr>Français</fr>
            </language>
        </languages>
        <capital>
            Ouagadougou
        </capital>
    </country>
    <country>
        <name>
            <en>Burundi
            </en>
            <fr>Burundi</fr>
        </name>
        <location>
            0,5
        </location>
        <territories>
            <territory/>
        </territories>
        <ownedLocation/>
        <acceptedNames>
            <name>
                <en>Burundi</en>
                <fr>Burundi</fr>
            </name>
        </acceptedNames>
        <flag>
            <svg>
                bi.svg
            </svg>

        </flag>
        <currency>
            BIF
        </currency>
        <languages>
            <language>
                <en>French</en>
                <fr>Français</fr>
            </language>
            <language>
                <en>Kirundi</en>
                <fr>Kirundi</fr>
            </language>
            <language>
                <en>English</en>
                <fr>Anglais</fr>
            </language>
        </languages>
        <capital>
            Gitega
        </capital>
    </country>
    <country>
        <name>
            <en>Cameroon
            </en>
            <fr>Cameroun</fr>
        </name>
        <location>
            0,6
        </location>
        <territories>
            <territory/>
        </territories>
        <ownedLocation/>
        <acceptedNames>
            <name>
                <en>Cameroon</en>
                <fr>Cameroun</fr>
            </name>
        </acceptedNames>
        <flag>
            <svg>
                cm.svg
            </svg>

        </flag>
        <currency>
            XAF
        </currency>
        <languages>
            <language>
                <en>English</en>
                <fr>Anglais</fr>
            </language>
        </languages>
        <capital>
            Yaounde
        </capital>
    </country>
    <country>
        <name>
            <en>Cape Verde
            </en>
            <fr>Cap-Vert</fr>
        </name>
        <location>
            0,7
        </location>
        <territories>
            <territory/>
        </territories>
        <ownedLocation/>
        <acceptedNames>
            <name>
                <en>Cape Verde</en>
                <fr>Cap-Vert</fr>
            </name>
        </acceptedNames>
        <flag>
            <svg>
                cv.svg
            </svg>

        </flag>
        <currency>
            CVE
        </currency>
        <languages>
            <language>
                <en>Portuguese</en>
                <fr>portugais</fr>
            </language>
        </languages>
        <capital>
            Praia
        </capital>
    </country>
    <country>
        <name>
            <en>Central African Republic
            </en>
            <fr>République centrafricaine</fr>
        </name>
        <location>
            0,8
        </location>
        <territories>
            <territory/>
        </territories>
        <ownedLocation/>
        <acceptedNames>
            <name>
                <en>Central African Republic</en>
                <fr>République centrafricaine</fr>
            </name>
            <name>
                <en>car</en>
                <fr>car</fr>
            </name>
        </acceptedNames>
        <flag>
            <svg>
                cf.svg
            </svg>

        </flag>
        <currency>
            XAF
        </currency>
        <languages>
            <language>
                <en>French</en>
                <fr>Français</fr>
            </language>
        </languages>
        <capital>
            Bangui
        </capital>
    </country>
    <country>
        <name>
            <en>Chad
            </en>
            <fr>Tchad</fr>
        </name>
        <location>
            0,9
        </location>
        <territories>
            <territory/>
        </territories>
        <ownedLocation/>
        <acceptedNames>
            <name>
                <en>Chad</en>
                <fr>Tchad</fr>
            </name>
        </acceptedNames>
        <flag>
            <svg>
                td.svg
            </svg>

        </flag>
        <currency>
            XAF
        </currency>
        <languages>
            <language>
                <en>Arabic</en>
                <fr>arabe</fr>
            </language>
            <language>
                <en>French</en>
                <fr>Français</fr>
            </language>
        </languages>
        <capital>
            N'Djamena
        </capital>
    </country>
    <country>
        <name>
            <en>Comoros
            </en>
            <fr>Comores</fr>
        </name>
        <location>
            0,10
        </location>
        <territories>
            <territory/>
        </territories>
        <ownedLocation/>
        <acceptedNames>
            <name>
                <en>Comoros</en>
                <fr>Comores</fr>
            </name>
        </acceptedNames>
        <flag>
            <svg>
                km.svg
            </svg>

        </flag>
        <currency>
            KMF
        </currency>
        <languages>
            <language>
                <en>Arabic</en>
                <fr>arabe</fr>
            </language>
            <language>
                <en>Comorian</en>
                <fr>Comorien</fr>
            </language>
            <language>
                <en>French</en>
                <fr>Français</fr>
            </language>
        </languages>
        <capital>
            Moroni
        </capital>
    </country>
    <country>
        <name>
            <en>Congo
            </en>
            <fr>Congo</fr>
        </name>
        <location>
